// ─────────────────────────────────────────────────────────
// Noble Hart CMS — public API config
// ─────────────────────────────────────────────────────────
// Paste your CMS Apps Script Web App's public URL here (the "Anyone"
// deployment — Deployment B in SECURITY.md). It looks like:
// https://script.google.com/macros/s/AKfycb.../exec
//
// Used by every page that talks to the CMS: blog.html, books.html,
// freebies.html, about.html, and every individual post page (via
// cms-engine.js). Post pages generated by GitHub auto-publish already
// have the CMS URL baked in separately — this file doesn't affect them.
const CMS_API_URL = "https://script.google.com/macros/s/AKfycbwy951w8IFhDDGr0Hx7vJc6YjfhhOKY0Mtuo8om36_lHoQDAvVRX-fjPvupFRQOsOF4/exec";

// Optional, but recommended once your site has real visitors: a
// reCAPTCHA v3 site key, free from Google, used to invisibly verify
// that a like/comment/download/email-capture request is actually coming
// from a human browser, not a script. See SPAM_PROTECTION_SETUP.md for
// how to get one. Leave the placeholder below and this feature simply
// stays off — nothing else on the site depends on it.
const RECAPTCHA_SITE_KEY = "PASTE_YOUR_RECAPTCHA_SITE_KEY_HERE";
